---
title: "A Data Approach to Ingredient Discovery for Consumer Packaged Goods (CPG)"
author: "Zhichao Hu"
date: "May 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(tabulizer)
library(openxlsx)
library(knitr)
library(kableExtra)
library(ggthemes)
library(plotly)
library(gtrendsR)
```
## This file is used to generate the tables and figures for the project summary report.

```{r echo = FALSE, message = FALSE}
chemical_cas <- read_csv("chemical_cas.csv")
```

### Table 1
```{r echo = FALSE, message = FALSE, results = "asis"}
chemical_cas %>% arrange(desc(score)) %>% .[1:5,] %>% kable(format = "html", row.names = FALSE, align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F, font_size = 12)
```


```{r echo = FALSE, message = FALSE}
chemical_product <- read_csv("2_cscpopendata.csv")
```

```{r echo = FALSE, message = FALSE}
company_citation <- chemical_product %>% group_by(CompanyName) %>% summarise(citation = n()) %>% 
  arrange(desc(citation)) %>% .[1:20,]
company_citation$CompanyName <- factor(company_citation$CompanyName,levels = company_citation$CompanyName)

brand_citation <- chemical_product %>% select(BrandName)
brand_citation$BrandName <- str_replace(brand_citation$BrandName,"SEPHORA", "Sephora")
brand_citation <- brand_citation %>% group_by(BrandName) %>% summarise(citation = n()) %>% 
  arrange(desc(citation)) %>% .[1:20,]
brand_citation$BrandName <- factor(brand_citation$BrandName, levels = brand_citation$BrandName)

category_citation <- chemical_product %>% group_by(PrimaryCategory) %>% summarise(citation = n()) %>% 
  arrange(desc(citation))
```

### Figure 1
<div class="centered">
```{r echo = FALSE, message = FALSE}
ggplot(company_citation, aes(reorder(CompanyName, citation), citation, fill = CompanyName)) + 
  geom_col(show.legend = FALSE) + xlab(NULL) + coord_flip() + ggtitle("Top 20 Most Cited Companies") +
  theme(plot.title = element_text(hjust = 0.5)) + theme_economist() + scale_fill_hue(l = 50)
```
</div>

### Figure 2
<div class="centered">
```{r echo = FALSE, message = FALSE}
ggplot(brand_citation, aes(reorder(BrandName, citation), citation, fill = BrandName)) + 
  geom_col(show.legend = FALSE) + xlab(NULL) + coord_flip() + ggtitle("Top 20 Most Cited Brands") +
  theme(plot.title = element_text(hjust = 0.5)) + theme_economist() + scale_fill_hue(l = 50)
```
</div>

### Figure 3
<div class="centered">
```{r echo = FALSE, message = FALSE}
plot_ly(category_citation, labels = ~PrimaryCategory, values = ~citation) %>% 
  add_pie(hole = 0.6) %>% 
  layout(title = "Primary Category by Citation",  showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```
</div>

```{r echo = FALSE, message = TRUE}
oral_care <- chemical_product %>% filter(PrimaryCategory == "Oral Hygiene Products")
```

### Table 2
```{r echo = FALSE, message = TRUE}
oral_care$ProductName <- str_replace(oral_care$ProductName, "Burt.s", "Burt's")
oral_care$BrandName <- str_replace(oral_care$BrandName, "Burt.s", "Burt's")
oral_care_cas <- oral_care %>% filter(CasNumber != "")
oral_care %>% group_by(CasNumber, ChemicalName) %>% summarise(citation = n()) %>% arrange(desc(citation)) %>% 
  kable(format = "html", row.names = FALSE, align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F, font_size = 12)
```

### Table 3
```{r echo = FALSE, message = TRUE}
oral_care_cas %>% group_by(CasNumber, ChemicalName) %>% summarise(citation = n()) %>% 
  inner_join(chemical_cas, by = c("CasNumber" = "cas")) %>% 
  kable(format = "html", row.names = FALSE, align = "c", col.names = c("cas", "name", "citation", "cancer", "developmental", "female<br/>reproductive", "male<br/>reproductive", "score"), escape = FALSE) %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F, font_size = 12)
```

```{r echo = FALSE, message = TRUE, cache = TRUE}
tio2_trend <- gtrends("Titanium dioxide", geo = "US", time = "today 12-m")
#taylor_trend <- gtrends("Taylor Swift", geo = "US")
tio2_toothpaste <- gtrends(c("Titanium dioxide", "Toothpaste"), geo = "US", time = "today 12-m")

tio2_toothpaste_trend <- tio2_toothpaste$interest_over_time

tio2_toothpaste_trend_1 <- tio2_toothpaste_trend %>% filter(keyword == "Titanium dioxide")

tio2_toothpaste_trend_2 <- tio2_toothpaste_trend %>% filter(keyword == "Toothpaste")

date <- tio2_toothpaste_trend_1$date

tio2_hits <- tio2_toothpaste_trend_1$hits %>% str_replace("<1", "0") %>% as.integer()

toothpaste_hits <- tio2_toothpaste_trend_2$hits %>% as.integer()

tio2_toothpaste_df <- data.frame(date, tio2_hits, toothpaste_hits)

names(tio2_toothpaste_df) <- c("date", "Titanium dioxide", "Toothpaste")

```

### Figure 4
<div class="centered">
```{r echo = FALSE, message = TRUE}
plot_ly(tio2_toothpaste_df, x = ~date, y = ~tio2_hits, type = "scatter", mode = "lines", name = "Titanium dioxide", 
        line = list(color = "blue", width = 4)) %>% 
  add_trace(y = ~toothpaste_hits, name = "Toothpaste", line = list(color = "red", width = 4)) %>% 
  layout(title = "Relative Search Interest over Time (US)",  showlegend = T,
         xaxis = list(title = FALSE),
         yaxis = list(title = "Relative Interest"))
```
</div>

### Table 4
```{r echo = FALSE, message = TRUE}
tio2_trend[["related_queries"]] %>% filter(related_queries == "top") %>% select(subject, value) %>% 
  plyr::rename(c("subject" = "relative_interest","value" = "query")) %>% 
  filter(relative_interest == "100"|str_detect(query, "safe|cancer|bad|dangers|toxic|allergy")) %>% 
  kable(format = "html", row.names = FALSE, align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F, font_size = 12)
```

```{r echo = FALSE, message = TRUE, cache = TRUE}
chemical_use <- read.xlsx("3_cpcat_chemicals.xlsx", sheet = 1)
#chemical_use %>%  filter(CASRN == " 13463-67-7") %>% select(Description_CPCAT) %>% distinct() %>% nrow()
```

### Table 5
<div class="centered">
```{r echo = FALSE, message = TRUE, results = "asis"}
chemical_color <- chemical_use %>% filter(Description_CPCAT == "personal_care cosmetics colorant") %>%
  select(CASRN, Name) %>% distinct()
chemical_color$CASRN <- chemical_color$CASRN %>% str_replace(" ", "")
chemical_color_safe <- anti_join(chemical_color, chemical_cas, by = c("CASRN" = "cas"))
chemical_color_safe %>% .[c(30,46,100,118,163,164),] %>% 
  kable(format = "html", row.names = FALSE, align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = F, font_size = 12)

#write_csv(chemical_color, "chemical_color.csv")
#write_csv(chemical_color_safe, "chemical_color_safe.csv")
```
</div>